config/routes.rb
Rails.application.routes.draw do
  resources :terminals

end

app/models/terminal.rb
class Terminal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/terminals_controller.rb
class TerminalsController < ApplicationController
  before_action :set_terminal, only: [:show, :edit, :update, :destroy]

  # GET /terminals
  # GET /terminals.json
  def index
    @terminals = Terminal.all
    respond_to do |format|
      format.html
      format.json
      format.xml {render :xml => @terminals }
    end
  end

  # GET /terminals/1
  # GET /terminals/1.json
  def show
  end

  # GET /terminals/new
  def new
    @terminal = Terminal.new
  end

  # GET /terminals/1/edit
  def edit
  end

  # POST /terminals
  # POST /terminals.json
  def create
    @terminal = Terminal.new(terminal_params)

    respond_to do |format|
      if @terminal.save
        format.html { redirect_to @terminal, notice: 'Terminal was successfully created.' }
        format.json { render :show, status: :created, location: @terminal }
      else
        format.html { render :new }
        format.json { render json: @terminal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terminals/1
  # PATCH/PUT /terminals/1.json
  def update
    respond_to do |format|
      if @terminal.update(terminal_params)
        format.html { redirect_to @terminal, notice: 'Terminal was successfully updated.' }
        format.json { render :show, status: :ok, location: @terminal }
      else
        format.html { render :edit }
        format.json { render json: @terminal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terminals/1
  # DELETE /terminals/1.json
  def destroy
    @terminal.destroy
    respond_to do |format|
      format.html { redirect_to terminals_url, notice: 'Terminal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_terminal
      @terminal = Terminal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def terminal_params
      params.require(:terminal).permit(:name, :description, :other_attributes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/terminals_helper.rb
module TerminalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppTerminal2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/terminals/_form.html.erb
<%= form_for(@terminal) do |f| %>
  <% if @terminal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@terminal.errors.count, "error") %> prohibited this terminal from being saved:</h2>

      <ul>
      <% @terminal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :other_attributes %><br>
    <%= f.text_area :other_attributes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/terminals/edit.html.erb
<h1>Editing terminal</h1>

<%= render 'form' %>

<%= link_to 'Show', @terminal %> |
<%= link_to 'Back', terminals_path %>

app/views/terminals/index.html.erb
<h1>Listing terminals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Other attributes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @terminals.each do |terminal| %>
      <tr>
        <td><%= terminal.name %></td>
        <td><%= terminal.description %></td>
        <td><%= terminal.other_attributes %></td>
        <td><%= link_to 'Show', terminal %></td>
        <td><%= link_to 'Edit', edit_terminal_path(terminal) %></td>
        <td><%= link_to 'Destroy', terminal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Terminal', new_terminal_path %>

app/views/terminals/new.html.erb
<h1>New terminal</h1>

<%= render 'form' %>

<%= link_to 'Back', terminals_path %>

app/views/terminals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @terminal.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @terminal.description %>
</p>

<p>
  <strong>Other attributes:</strong>
  <%= @terminal.other_attributes %>
</p>

<%= link_to 'Edit', edit_terminal_path(@terminal) %> |
<%= link_to 'Back', terminals_path %>